name: container worflow
on: push  
jobs: 
  docker-steps:
    runs-on: ubuntu-latest
    container: 
      image: node:10.18.0-jessie
    steps:
      - name: post user
        run: 
          node -v
      - name: step with docker
        uses: docker://node:12.14.1.-alpine3.10
        with: 
          entrypoint: '/bin/echo'
          args: 'hello world'
      - name: step with docker
        uses: docker://node:12.14.1.-alpine3.10
        with: 
          entrypoint: '/usr/local/bin/mode'
          args: -v
  node-docker:
    runs-on: ubuntu-latest
    services: 
      app: 
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: post user
        run: 
          "curl -X POST 'http://localhost:3001/api/user' --header 'Content-Type: application/json' --data-raw '{    \"username\" :\"jordan\",    \"address\": \"meuendereco\"}'"
      - name: get user    
        run: curl http://localhost:3001/api/users
          
          
        