name: container worflow
on: push  
jobs: 
  node-docker:
    runs-on: ubuntu-latest
    services: 
      app: 
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: post user
        run: 
          "curl -X POST 'http://localhost:3001/api/user' --header 'Content-Type: application/json' --data-raw '{    \"username\" :\"jordan\",    \"address\": \"meuendereco\"}'"
      - name: get user    
        run: curl http://localhost:3001/api/users
          
          
        