name: maxtrix worflow
on: push  
jobs: 
  node-version:
    strategy:
      matrix:
        node_v: [6,8,10]
        include: 
          - node_v: 10
            is_node_10: "salve "
        exclude: 
          - node_v: 8
      fail-fast: true      
      max-parallel: 3
    runs-on: ubuntu-latest
    env: 
      nodev: ${{ matrix.is_node_10 }}    
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_v }}
      - name: Log node node-version        
        run: 
          echo ${nodev}
          node -v
          
          
        