name: maxtrix worflow
on: push  
jobs: 
  node-version:
    strategy:
      matrix:
        node_v: [6,8,10]
        node_v1: [1,2,3,4,5]
      fail-fast: true      
      max-parallel: 3
    runs-on: ubuntu-latest
    steps:
      - name: Log node node-version
        run: |
          node -v
      - uses: actions/setup-node@v1
        with:
          node-version: 6
      - name: Log node node-version
        run: node -v