name: Ãctions workflows
on: [push]
jobs:
  run-githubaction:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-meu-step 
        uses: actions/checkout@v1
      - name: comandim pus falado
        run: |
          pwd
          ls -a
      - name: Simple JS ACtion
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Jordan 
        id: greet
      - name: Log greeting time
        run: echo "${{steps.greet.outputs.time}}"