name: Ãctions workflows
on:
  repository_dispatch:
  pull_request:
    types: [opened]   
jobs:
  run-githubaction:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-meu-step 
        uses: actions/checkout@v1
      - name: comandim pus falado
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"
#          git clone git@github:GITHUB_REPOSITORY
#          git checkout $GITHUB_SHA
      - name: Simple JS ACtion
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Jordan 
        id: greet
      - name: Log greeting time
        run: echo "${{steps.greet.outputs.time}}"