name: Shell Commands
on: 
  workflow_dispatch:    
jobs:
  meu-job:
    runs-on: ubuntu-latest
    steps: 
      - name: ecoando frase
        run: echo "salve comunidade"
      - name: multiline scripts
        run: |
          node -v
          npm -v 
      - name: python command
        run: |
          import platform 
          print(platform.processor())
        shell: python
  meu-job-windows:
    runs-on: windows-latest
    needs: ['meu-job']
    steps:
      - name: Directory powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
    