name: Shell Commands
on: [push]
jobs:
  meu-job:
    runs-on: ubuntu-latest
    steps: 
      - name: ecoando frase
        run: ec1ho "salve comunidade"
      - name: multiline scripts
        run: |
          node -v
          npm -v 